import { ITEM_TYPE } from "../utils/item.js";
import { FIELD_TYPE } from "../utils/render.js";
import { MODULE_SHORT } from "./const.js";

/**
 * A set of configuration details that are globally used throughout the module.
 * This currently includes valid item types for roll configuration and default configuration flags.
 */
CONFIG[MODULE_SHORT] = {
    validItemTypes: [
        ITEM_TYPE.WEAPON,
        ITEM_TYPE.SPELL,
        ITEM_TYPE.EQUIPMENT,
        ITEM_TYPE.FEATURE,
        ITEM_TYPE.TOOL,
        ITEM_TYPE.CONSUMABLE,
        ITEM_TYPE.ADVENTURINGGEAR,
        ITEM_TYPE.AMMO,
        ITEM_TYPE.ARCHETYPEFEATURES,
        ITEM_TYPE.ARCHETYPES,
        ITEM_TYPE.ARMOR,
        ITEM_TYPE.BACKGROUNDS,
        ITEM_TYPE.BLASTERS,
        ITEM_TYPE.CLASSES,
        ITEM_TYPE.CLASSFEATURES,
        ITEM_TYPE.CONSUMABLES,
        ITEM_TYPE.DEPLOYMENTFEATURES,
        ITEM_TYPE.DEPLOYMENTS,
        ITEM_TYPE.ENHANCEDITEMS,
        ITEM_TYPE.EXPLOSIVES,
        ITEM_TYPE.FEATS,
        ITEM_TYPE.FIGHTINGSTYLES,
        ITEM_TYPE.FIGHTINGMASTERIES,
        ITEM_TYPE.GAMINGSETS,
        ITEM_TYPE.IMPLEMENTS,
        ITEM_TYPE.INVOCATIONS,
        ITEM_TYPE.KITS,
        ITEM_TYPE.LIGHTSABERFORM,
        ITEM_TYPE.LIGHTWEAPONS,
        ITEM_TYPE.MANEUVERS,
        ITEM_TYPE.MONSTERTRAITS,
        ITEM_TYPE.MODIFICATIONS,
        ITEM_TYPE.MUSICALINSTRUMENTS,
        ITEM_TYPE.SPECIES,
        ITEM_TYPE.SPECIESFEATURES,
        ITEM_TYPE.STARSHIPACTIONS,
        ITEM_TYPE.STARSHIPARMOR,
        ITEM_TYPE.STARSHIPEQUIPMENT,
        ITEM_TYPE.STARSHIPFEATURES,
        ITEM_TYPE.STARSHIPMODIFICATIONS,
        ITEM_TYPE.STARSHIPS,
        ITEM_TYPE.STARSHIPWEAPONS,
        ITEM_TYPE.POWER,
        ITEM_TYPE.VENTURES,
        ITEM_TYPE.VIBROWEAPONS
    ],
    validMultiRollFields: [
        FIELD_TYPE.ATTACK,
        FIELD_TYPE.CHECK
    ],
    validDamageRollFields: [
        FIELD_TYPE.DAMAGE
    ],
    defaultQuickRollParams: {
        forceCrit: false,
        forceFumble: false,
        forceMultiRoll: false,
        hasAdvantage: false,
        hasDisadvantage: false
    },
    flags: {
        weapon: {
            quickDesc: { type: "Boolean", value: false, altValue: false },
            quickFlavor: { type: "Boolean", value: true, altValue: true },
            quickFooter: { type: "Boolean", value: true, altValue: true },
            quickAttack: { type: "Boolean", value: true, altValue: true },
            quickSave: { type: "Boolean", value: true, altValue: true },
            quickCheck: { type: "Boolean", value: true, altValue: true },
            quickVersatile: { type: "Boolean", value: false, altValue: true },
            quickTemplate: { type: "Boolean", value: true, altValue: true },
            quickDamage: { type: "Array", value: [], altValue: [], context: [] },
            quickOther: { type: "Boolean", value: true, altValue: true, context: "" },
            consumeQuantity: { type: "Boolean", value: false, altValue: false },
            consumeUses: { type: "Boolean", value: false, altValue: true },
            consumeResource: { type: "Boolean", value: true, altValue: true }
        },
        spell: {
            quickDesc: { type: "Boolean", value: true, altValue: true },
            quickFlavor: { type: "Boolean", value: true, altValue: true },
            quickFooter: { type: "Boolean", value: true, altValue: true },
            quickAttack: { type: "Boolean", value: true, altValue: true },
            quickVersatile: { type: "Boolean", value: false, altValue: false },
            quickSave: { type: "Boolean", value: true, altValue: true },
            quickDamage: { type: "Array", value: [], altValue: [], context: [] },
            quickOther: { type: "Boolean", value: true, altValue: true, context: "" }
        },
        equipment: {
            quickDesc: { type: "Boolean", value: true, altValue: true },
            quickFlavor: { type: "Boolean", value: true, altValue: true },
            quickFooter: { type: "Boolean", value: true, altValue: true },
            quickAttack: { type: "Boolean", value: true, altValue: true },
            quickTemplate: { type: "Boolean", value: true, altValue: true },
            quickSave: { type: "Boolean", value: true, altValue: true },
            quickDamage: { type: "Array", value: [], altValue: [], context: [] },
            quickOther: { type: "Boolean", value: true, altValue: true, context: "" },
            consumeQuantity: { type: "Boolean", value: false, altValue: false },
            consumeUses: { type: "Boolean", value: false, altValue: true },
            consumeResource: { type: "Boolean", value: false, altValue: true }
        },
        feat: {
            quickDesc: { type: "Boolean", value: true, altValue: true },
            quickFlavor: { type: "Boolean", value: true, altValue: true },
            quickFooter: { type: "Boolean", value: true, altValue: true },
            quickAttack: { type: "Boolean", value: true, altValue: true },
            quickTemplate: { type: "Boolean", value: true, altValue: true },
            quickSave: { type: "Boolean", value: true, altValue: true },
            quickDamage: { type: "Array", value: [], altValue: [], context: [] },
            quickOther: { type: "Boolean", value: true, altValue: true, context: "" },
            consumeQuantity: { type: "Boolean", value: true, altValue: true },
            consumeUses: { type: "Boolean", value: true, altValue: true },
            consumeResource: { type: "Boolean", value: true, altValue: true },
            consumeRecharge: { type: "Boolean", value: true, altValue: true }
        },
        tool: {
            quickDesc: { type: "Boolean", value: false, altValue: false },
            quickFlavor: { type: "Boolean", value: true, altValue: true },
            quickFooter: { type: "Boolean", value: true, altValue: true },
            quickCheck: { type: "Boolean", value: true, altValue: true }
        },
        consumable: {
            quickDesc: { type: "Boolean", value: true, altValue: true },
            quickFlavor: { type: "Boolean", value: true, altValue: true },
            quickFooter: { type: "Boolean", value: true, altValue: true },
            quickAttack: { type: "Boolean", value: true, altValue: true },
            quickTemplate: { type: "Boolean", value: true, altValue: true },
            quickSave: { type: "Boolean", value: true, altValue: true },
            quickDamage: { type: "Array", value: [], altValue: [], context: [] },
            quickOther: { type: "Boolean", value: true, altValue: true, context: "" },
            consumeQuantity: { type: "Boolean", value: true, altValue: true },
            consumeUses: { type: "Boolean", value: true, altValue: true },
            consumeResource: { type: "Boolean", value: true, altValue: true }
        },
        adventuringgear: {
            quickDesc: { type: "Boolean", value: true, altValue: true },
            quickFlavor: { type: "Boolean", value: true, altValue: true },
            quickFooter: { type: "Boolean", value: true, altValue: true },
            quickAttack: { type: "Boolean", value: true, altValue: true },
            quickTemplate: { type: "Boolean", value: true, altValue: true },
            quickSave: { type: "Boolean", value: true, altValue: true },
            quickDamage: { type: "Array", value: [], altValue: [], context: [] },
            quickOther: { type: "Boolean", value: true, altValue: true, context: "" },
            consumeQuantity: { type: "Boolean", value: false, altValue: false },
            consumeUses: { type: "Boolean", value: false, altValue: true },
            consumeResource: { type: "Boolean", value: false, altValue: true }
        },
        ammo: {
            quickDesc: { type: "Boolean", value: true, altValue: true },
            quickFlavor: { type: "Boolean", value: true, altValue: true },
            quickFooter: { type: "Boolean", value: true, altValue: true },
            quickAttack: { type: "Boolean", value: true, altValue: true },
            quickTemplate: { type: "Boolean", value: true, altValue: true },
            quickSave: { type: "Boolean", value: true, altValue: true },
            quickDamage: { type: "Array", value: [], altValue: [], context: [] },
            quickOther: { type: "Boolean", value: true, altValue: true, context: "" },
            consumeQuantity: { type: "Boolean", value: true, altValue: true },
            consumeUses: { type: "Boolean", value: true, altValue: true },
            consumeResource: { type: "Boolean", value: true, altValue: true }
        },
        archetypefeatures: {
            quickDesc: { type: "Boolean", value: true, altValue: true },
            quickFlavor: { type: "Boolean", value: true, altValue: true },
            quickFooter: { type: "Boolean", value: true, altValue: true },
            quickAttack: { type: "Boolean", value: true, altValue: true },
            quickTemplate: { type: "Boolean", value: true, altValue: true },
            quickSave: { type: "Boolean", value: true, altValue: true },
            quickDamage: { type: "Array", value: [], altValue: [], context: [] },
            quickOther: { type: "Boolean", value: true, altValue: true, context: "" },
            consumeQuantity: { type: "Boolean", value: true, altValue: true },
            consumeUses: { type: "Boolean", value: true, altValue: true },
            consumeResource: { type: "Boolean", value: true, altValue: true },
            consumeRecharge: { type: "Boolean", value: true, altValue: true }
        },
        archetypes: {
            quickDesc: { type: "Boolean", value: true, altValue: true },
            quickFlavor: { type: "Boolean", value: true, altValue: true },
            quickFooter: { type: "Boolean", value: true, altValue: true },
            quickAttack: { type: "Boolean", value: true, altValue: true },
            quickTemplate: { type: "Boolean", value: true, altValue: true },
            quickSave: { type: "Boolean", value: true, altValue: true },
            quickDamage: { type: "Array", value: [], altValue: [], context: [] },
            quickOther: { type: "Boolean", value: true, altValue: true, context: "" },
            consumeQuantity: { type: "Boolean", value: true, altValue: true },
            consumeUses: { type: "Boolean", value: true, altValue: true },
            consumeResource: { type: "Boolean", value: true, altValue: true },
            consumeRecharge: { type: "Boolean", value: true, altValue: true }
        },
        armor: {
            quickDesc: { type: "Boolean", value: true, altValue: true },
            quickFlavor: { type: "Boolean", value: true, altValue: true },
            quickFooter: { type: "Boolean", value: true, altValue: true },
            quickAttack: { type: "Boolean", value: true, altValue: true },
            quickTemplate: { type: "Boolean", value: true, altValue: true },
            quickSave: { type: "Boolean", value: true, altValue: true },
            quickDamage: { type: "Array", value: [], altValue: [], context: [] },
            quickOther: { type: "Boolean", value: true, altValue: true, context: "" },
            consumeQuantity: { type: "Boolean", value: false, altValue: false },
            consumeUses: { type: "Boolean", value: false, altValue: true },
            consumeResource: { type: "Boolean", value: false, altValue: true }
        },
        backgrounds: {
            quickDesc: { type: "Boolean", value: true, altValue: true },
            quickFlavor: { type: "Boolean", value: true, altValue: true },
            quickFooter: { type: "Boolean", value: true, altValue: true },
            quickAttack: { type: "Boolean", value: true, altValue: true },
            quickTemplate: { type: "Boolean", value: true, altValue: true },
            quickSave: { type: "Boolean", value: true, altValue: true },
            quickDamage: { type: "Array", value: [], altValue: [], context: [] },
            quickOther: { type: "Boolean", value: true, altValue: true, context: "" },
            consumeQuantity: { type: "Boolean", value: true, altValue: true },
            consumeUses: { type: "Boolean", value: true, altValue: true },
            consumeResource: { type: "Boolean", value: true, altValue: true },
            consumeRecharge: { type: "Boolean", value: true, altValue: true }
        },
        blasters: {
            quickDesc: { type: "Boolean", value: false, altValue: false },
            quickFlavor: { type: "Boolean", value: true, altValue: true },
            quickFooter: { type: "Boolean", value: true, altValue: true },
            quickAttack: { type: "Boolean", value: true, altValue: true },
            quickSave: { type: "Boolean", value: true, altValue: true },
            quickCheck: { type: "Boolean", value: true, altValue: true },
            quickVersatile: { type: "Boolean", value: false, altValue: true },
            quickTemplate: { type: "Boolean", value: true, altValue: true },
            quickDamage: { type: "Array", value: [], altValue: [], context: [] },
            quickOther: { type: "Boolean", value: true, altValue: true, context: "" },
            consumeQuantity: { type: "Boolean", value: false, altValue: false },
            consumeUses: { type: "Boolean", value: false, altValue: true },
            consumeResource: { type: "Boolean", value: true, altValue: true }
        },
        classes: {
            quickDesc: { type: "Boolean", value: true, altValue: true },
            quickFlavor: { type: "Boolean", value: true, altValue: true },
            quickFooter: { type: "Boolean", value: true, altValue: true },
            quickAttack: { type: "Boolean", value: true, altValue: true },
            quickTemplate: { type: "Boolean", value: true, altValue: true },
            quickSave: { type: "Boolean", value: true, altValue: true },
            quickDamage: { type: "Array", value: [], altValue: [], context: [] },
            quickOther: { type: "Boolean", value: true, altValue: true, context: "" },
            consumeQuantity: { type: "Boolean", value: true, altValue: true },
            consumeUses: { type: "Boolean", value: true, altValue: true },
            consumeResource: { type: "Boolean", value: true, altValue: true },
            consumeRecharge: { type: "Boolean", value: true, altValue: true }
        },
        classfeatures: {
            quickDesc: { type: "Boolean", value: true, altValue: true },
            quickFlavor: { type: "Boolean", value: true, altValue: true },
            quickFooter: { type: "Boolean", value: true, altValue: true },
            quickAttack: { type: "Boolean", value: true, altValue: true },
            quickTemplate: { type: "Boolean", value: true, altValue: true },
            quickSave: { type: "Boolean", value: true, altValue: true },
            quickDamage: { type: "Array", value: [], altValue: [], context: [] },
            quickOther: { type: "Boolean", value: true, altValue: true, context: "" },
            consumeQuantity: { type: "Boolean", value: true, altValue: true },
            consumeUses: { type: "Boolean", value: true, altValue: true },
            consumeResource: { type: "Boolean", value: true, altValue: true },
            consumeRecharge: { type: "Boolean", value: true, altValue: true }
        },
        consumables: {
            quickDesc: { type: "Boolean", value: true, altValue: true },
            quickFlavor: { type: "Boolean", value: true, altValue: true },
            quickFooter: { type: "Boolean", value: true, altValue: true },
            quickAttack: { type: "Boolean", value: true, altValue: true },
            quickTemplate: { type: "Boolean", value: true, altValue: true },
            quickSave: { type: "Boolean", value: true, altValue: true },
            quickDamage: { type: "Array", value: [], altValue: [], context: [] },
            quickOther: { type: "Boolean", value: true, altValue: true, context: "" },
            consumeQuantity: { type: "Boolean", value: true, altValue: true },
            consumeUses: { type: "Boolean", value: true, altValue: true },
            consumeResource: { type: "Boolean", value: true, altValue: true }
        },
        deploymentfeatures: {
            quickDesc: { type: "Boolean", value: true, altValue: true },
            quickFlavor: { type: "Boolean", value: true, altValue: true },
            quickFooter: { type: "Boolean", value: true, altValue: true },
            quickAttack: { type: "Boolean", value: true, altValue: true },
            quickTemplate: { type: "Boolean", value: true, altValue: true },
            quickSave: { type: "Boolean", value: true, altValue: true },
            quickDamage: { type: "Array", value: [], altValue: [], context: [] },
            quickOther: { type: "Boolean", value: true, altValue: true, context: "" },
            consumeQuantity: { type: "Boolean", value: true, altValue: true },
            consumeUses: { type: "Boolean", value: true, altValue: true },
            consumeResource: { type: "Boolean", value: true, altValue: true },
            consumeRecharge: { type: "Boolean", value: true, altValue: true }
        },
        deployments: {
            quickDesc: { type: "Boolean", value: true, altValue: true },
            quickFlavor: { type: "Boolean", value: true, altValue: true },
            quickFooter: { type: "Boolean", value: true, altValue: true },
            quickAttack: { type: "Boolean", value: true, altValue: true },
            quickTemplate: { type: "Boolean", value: true, altValue: true },
            quickSave: { type: "Boolean", value: true, altValue: true },
            quickDamage: { type: "Array", value: [], altValue: [], context: [] },
            quickOther: { type: "Boolean", value: true, altValue: true, context: "" },
            consumeQuantity: { type: "Boolean", value: true, altValue: true },
            consumeUses: { type: "Boolean", value: true, altValue: true },
            consumeResource: { type: "Boolean", value: true, altValue: true },
            consumeRecharge: { type: "Boolean", value: true, altValue: true }
        },
        enhanceditems: {
            quickDesc: { type: "Boolean", value: true, altValue: true },
            quickFlavor: { type: "Boolean", value: true, altValue: true },
            quickFooter: { type: "Boolean", value: true, altValue: true },
            quickAttack: { type: "Boolean", value: true, altValue: true },
            quickTemplate: { type: "Boolean", value: true, altValue: true },
            quickSave: { type: "Boolean", value: true, altValue: true },
            quickDamage: { type: "Array", value: [], altValue: [], context: [] },
            quickOther: { type: "Boolean", value: true, altValue: true, context: "" },
            consumeQuantity: { type: "Boolean", value: false, altValue: false },
            consumeUses: { type: "Boolean", value: false, altValue: true },
            consumeResource: { type: "Boolean", value: false, altValue: true }
        },
        explosives: {
            quickDesc: { type: "Boolean", value: true, altValue: true },
            quickFlavor: { type: "Boolean", value: true, altValue: true },
            quickFooter: { type: "Boolean", value: true, altValue: true },
            quickAttack: { type: "Boolean", value: true, altValue: true },
            quickTemplate: { type: "Boolean", value: true, altValue: true },
            quickSave: { type: "Boolean", value: true, altValue: true },
            quickDamage: { type: "Array", value: [], altValue: [], context: [] },
            quickOther: { type: "Boolean", value: true, altValue: true, context: "" },
            consumeQuantity: { type: "Boolean", value: true, altValue: true },
            consumeUses: { type: "Boolean", value: true, altValue: true },
            consumeResource: { type: "Boolean", value: true, altValue: true }
        },
        feats: {
            quickDesc: { type: "Boolean", value: true, altValue: true },
            quickFlavor: { type: "Boolean", value: true, altValue: true },
            quickFooter: { type: "Boolean", value: true, altValue: true },
            quickAttack: { type: "Boolean", value: true, altValue: true },
            quickTemplate: { type: "Boolean", value: true, altValue: true },
            quickSave: { type: "Boolean", value: true, altValue: true },
            quickDamage: { type: "Array", value: [], altValue: [], context: [] },
            quickOther: { type: "Boolean", value: true, altValue: true, context: "" },
            consumeQuantity: { type: "Boolean", value: true, altValue: true },
            consumeUses: { type: "Boolean", value: true, altValue: true },
            consumeResource: { type: "Boolean", value: true, altValue: true },
            consumeRecharge: { type: "Boolean", value: true, altValue: true }
        },
        fightingstyles: {
            quickDesc: { type: "Boolean", value: true, altValue: true },
            quickFlavor: { type: "Boolean", value: true, altValue: true },
            quickFooter: { type: "Boolean", value: true, altValue: true },
            quickAttack: { type: "Boolean", value: true, altValue: true },
            quickTemplate: { type: "Boolean", value: true, altValue: true },
            quickSave: { type: "Boolean", value: true, altValue: true },
            quickDamage: { type: "Array", value: [], altValue: [], context: [] },
            quickOther: { type: "Boolean", value: true, altValue: true, context: "" },
            consumeQuantity: { type: "Boolean", value: true, altValue: true },
            consumeUses: { type: "Boolean", value: true, altValue: true },
            consumeResource: { type: "Boolean", value: true, altValue: true },
            consumeRecharge: { type: "Boolean", value: true, altValue: true }
        },
        fightingmasteries: {
            quickDesc: { type: "Boolean", value: true, altValue: true },
            quickFlavor: { type: "Boolean", value: true, altValue: true },
            quickFooter: { type: "Boolean", value: true, altValue: true },
            quickAttack: { type: "Boolean", value: true, altValue: true },
            quickTemplate: { type: "Boolean", value: true, altValue: true },
            quickSave: { type: "Boolean", value: true, altValue: true },
            quickDamage: { type: "Array", value: [], altValue: [], context: [] },
            quickOther: { type: "Boolean", value: true, altValue: true, context: "" },
            consumeQuantity: { type: "Boolean", value: true, altValue: true },
            consumeUses: { type: "Boolean", value: true, altValue: true },
            consumeResource: { type: "Boolean", value: true, altValue: true },
            consumeRecharge: { type: "Boolean", value: true, altValue: true }
        },
        gamingsets: {
            quickDesc: { type: "Boolean", value: false, altValue: false },
            quickFlavor: { type: "Boolean", value: true, altValue: true },
            quickFooter: { type: "Boolean", value: true, altValue: true },
            quickCheck: { type: "Boolean", value: true, altValue: true }
        },
        implements: {
            quickDesc: { type: "Boolean", value: false, altValue: false },
            quickFlavor: { type: "Boolean", value: true, altValue: true },
            quickFooter: { type: "Boolean", value: true, altValue: true },
            quickCheck: { type: "Boolean", value: true, altValue: true }
        },
        invocations: {
            quickDesc: { type: "Boolean", value: false, altValue: false },
            quickFlavor: { type: "Boolean", value: true, altValue: true },
            quickFooter: { type: "Boolean", value: true, altValue: true },
            quickCheck: { type: "Boolean", value: true, altValue: true }
        },
        kits: {
            quickDesc: { type: "Boolean", value: false, altValue: false },
            quickFlavor: { type: "Boolean", value: true, altValue: true },
            quickFooter: { type: "Boolean", value: true, altValue: true },
            quickCheck: { type: "Boolean", value: true, altValue: true }
        },
        lightsaberform: {
            quickDesc: { type: "Boolean", value: true, altValue: true },
            quickFlavor: { type: "Boolean", value: true, altValue: true },
            quickFooter: { type: "Boolean", value: true, altValue: true },
            quickAttack: { type: "Boolean", value: true, altValue: true },
            quickTemplate: { type: "Boolean", value: true, altValue: true },
            quickSave: { type: "Boolean", value: true, altValue: true },
            quickDamage: { type: "Array", value: [], altValue: [], context: [] },
            quickOther: { type: "Boolean", value: true, altValue: true, context: "" },
            consumeQuantity: { type: "Boolean", value: true, altValue: true },
            consumeUses: { type: "Boolean", value: true, altValue: true },
            consumeResource: { type: "Boolean", value: true, altValue: true },
            consumeRecharge: { type: "Boolean", value: true, altValue: true }
        },
        lightweapons: {
            quickDesc: { type: "Boolean", value: false, altValue: false },
            quickFlavor: { type: "Boolean", value: true, altValue: true },
            quickFooter: { type: "Boolean", value: true, altValue: true },
            quickAttack: { type: "Boolean", value: true, altValue: true },
            quickSave: { type: "Boolean", value: true, altValue: true },
            quickCheck: { type: "Boolean", value: true, altValue: true },
            quickVersatile: { type: "Boolean", value: false, altValue: true },
            quickTemplate: { type: "Boolean", value: true, altValue: true },
            quickDamage: { type: "Array", value: [], altValue: [], context: [] },
            quickOther: { type: "Boolean", value: true, altValue: true, context: "" },
            consumeQuantity: { type: "Boolean", value: false, altValue: false },
            consumeUses: { type: "Boolean", value: false, altValue: true },
            consumeResource: { type: "Boolean", value: true, altValue: true }
        },
        maneuvers: {
            quickDesc: { type: "Boolean", value: true, altValue: true },
            quickFlavor: { type: "Boolean", value: true, altValue: true },
            quickFooter: { type: "Boolean", value: true, altValue: true },
            quickAttack: { type: "Boolean", value: true, altValue: true },
            quickTemplate: { type: "Boolean", value: true, altValue: true },
            quickSave: { type: "Boolean", value: true, altValue: true },
            quickDamage: { type: "Array", value: [], altValue: [], context: [] },
            quickOther: { type: "Boolean", value: true, altValue: true, context: "" },
            consumeQuantity: { type: "Boolean", value: true, altValue: true },
            consumeUses: { type: "Boolean", value: true, altValue: true },
            consumeResource: { type: "Boolean", value: true, altValue: true },
            consumeRecharge: { type: "Boolean", value: true, altValue: true }
        },
        monstertraits: {
            quickDesc: { type: "Boolean", value: true, altValue: true },
            quickFlavor: { type: "Boolean", value: true, altValue: true },
            quickFooter: { type: "Boolean", value: true, altValue: true },
            quickAttack: { type: "Boolean", value: true, altValue: true },
            quickTemplate: { type: "Boolean", value: true, altValue: true },
            quickSave: { type: "Boolean", value: true, altValue: true },
            quickDamage: { type: "Array", value: [], altValue: [], context: [] },
            quickOther: { type: "Boolean", value: true, altValue: true, context: "" },
            consumeQuantity: { type: "Boolean", value: true, altValue: true },
            consumeUses: { type: "Boolean", value: true, altValue: true },
            consumeResource: { type: "Boolean", value: true, altValue: true },
            consumeRecharge: { type: "Boolean", value: true, altValue: true }
        },
        modifications: {
            quickDesc: { type: "Boolean", value: true, altValue: true },
            quickFlavor: { type: "Boolean", value: true, altValue: true },
            quickFooter: { type: "Boolean", value: true, altValue: true },
            quickAttack: { type: "Boolean", value: true, altValue: true },
            quickTemplate: { type: "Boolean", value: true, altValue: true },
            quickSave: { type: "Boolean", value: true, altValue: true },
            quickDamage: { type: "Array", value: [], altValue: [], context: [] },
            quickOther: { type: "Boolean", value: true, altValue: true, context: "" },
            consumeQuantity: { type: "Boolean", value: false, altValue: false },
            consumeUses: { type: "Boolean", value: false, altValue: true },
            consumeResource: { type: "Boolean", value: false, altValue: true }
        },
        musicalinstruments: {
            quickDesc: { type: "Boolean", value: false, altValue: false },
            quickFlavor: { type: "Boolean", value: true, altValue: true },
            quickFooter: { type: "Boolean", value: true, altValue: true },
            quickCheck: { type: "Boolean", value: true, altValue: true }
        },
        species: {
            quickDesc: { type: "Boolean", value: true, altValue: true },
            quickFlavor: { type: "Boolean", value: true, altValue: true },
            quickFooter: { type: "Boolean", value: true, altValue: true },
            quickAttack: { type: "Boolean", value: true, altValue: true },
            quickTemplate: { type: "Boolean", value: true, altValue: true },
            quickSave: { type: "Boolean", value: true, altValue: true },
            quickDamage: { type: "Array", value: [], altValue: [], context: [] },
            quickOther: { type: "Boolean", value: true, altValue: true, context: "" },
            consumeQuantity: { type: "Boolean", value: true, altValue: true },
            consumeUses: { type: "Boolean", value: true, altValue: true },
            consumeResource: { type: "Boolean", value: true, altValue: true },
            consumeRecharge: { type: "Boolean", value: true, altValue: true }
        },
        speciesfeatures: {
            quickDesc: { type: "Boolean", value: true, altValue: true },
            quickFlavor: { type: "Boolean", value: true, altValue: true },
            quickFooter: { type: "Boolean", value: true, altValue: true },
            quickAttack: { type: "Boolean", value: true, altValue: true },
            quickTemplate: { type: "Boolean", value: true, altValue: true },
            quickSave: { type: "Boolean", value: true, altValue: true },
            quickDamage: { type: "Array", value: [], altValue: [], context: [] },
            quickOther: { type: "Boolean", value: true, altValue: true, context: "" },
            consumeQuantity: { type: "Boolean", value: true, altValue: true },
            consumeUses: { type: "Boolean", value: true, altValue: true },
            consumeResource: { type: "Boolean", value: true, altValue: true },
            consumeRecharge: { type: "Boolean", value: true, altValue: true }
        },
        starshiparmor: {
            quickDesc: { type: "Boolean", value: true, altValue: true },
            quickFlavor: { type: "Boolean", value: true, altValue: true },
            quickFooter: { type: "Boolean", value: true, altValue: true },
            quickAttack: { type: "Boolean", value: true, altValue: true },
            quickTemplate: { type: "Boolean", value: true, altValue: true },
            quickSave: { type: "Boolean", value: true, altValue: true },
            quickDamage: { type: "Array", value: [], altValue: [], context: [] },
            quickOther: { type: "Boolean", value: true, altValue: true, context: "" },
            consumeQuantity: { type: "Boolean", value: false, altValue: false },
            consumeUses: { type: "Boolean", value: false, altValue: true },
            consumeResource: { type: "Boolean", value: false, altValue: true }
        },
        starshipequipment: {
            quickDesc: { type: "Boolean", value: true, altValue: true },
            quickFlavor: { type: "Boolean", value: true, altValue: true },
            quickFooter: { type: "Boolean", value: true, altValue: true },
            quickAttack: { type: "Boolean", value: true, altValue: true },
            quickTemplate: { type: "Boolean", value: true, altValue: true },
            quickSave: { type: "Boolean", value: true, altValue: true },
            quickDamage: { type: "Array", value: [], altValue: [], context: [] },
            quickOther: { type: "Boolean", value: true, altValue: true, context: "" },
            consumeQuantity: { type: "Boolean", value: false, altValue: false },
            consumeUses: { type: "Boolean", value: false, altValue: true },
            consumeResource: { type: "Boolean", value: false, altValue: true }
        },
        starshipfeatures: {
            quickDesc: { type: "Boolean", value: true, altValue: true },
            quickFlavor: { type: "Boolean", value: true, altValue: true },
            quickFooter: { type: "Boolean", value: true, altValue: true },
            quickAttack: { type: "Boolean", value: true, altValue: true },
            quickTemplate: { type: "Boolean", value: true, altValue: true },
            quickSave: { type: "Boolean", value: true, altValue: true },
            quickDamage: { type: "Array", value: [], altValue: [], context: [] },
            quickOther: { type: "Boolean", value: true, altValue: true, context: "" },
            consumeQuantity: { type: "Boolean", value: true, altValue: true },
            consumeUses: { type: "Boolean", value: true, altValue: true },
            consumeResource: { type: "Boolean", value: true, altValue: true },
            consumeRecharge: { type: "Boolean", value: true, altValue: true }
        },
        starshipmodifications: {
            quickDesc: { type: "Boolean", value: true, altValue: true },
            quickFlavor: { type: "Boolean", value: true, altValue: true },
            quickFooter: { type: "Boolean", value: true, altValue: true },
            quickAttack: { type: "Boolean", value: true, altValue: true },
            quickTemplate: { type: "Boolean", value: true, altValue: true },
            quickSave: { type: "Boolean", value: true, altValue: true },
            quickDamage: { type: "Array", value: [], altValue: [], context: [] },
            quickOther: { type: "Boolean", value: true, altValue: true, context: "" },
            consumeQuantity: { type: "Boolean", value: false, altValue: false },
            consumeUses: { type: "Boolean", value: false, altValue: true },
            consumeResource: { type: "Boolean", value: false, altValue: true }
        },
        starships: {
            quickDesc: { type: "Boolean", value: true, altValue: true },
            quickFlavor: { type: "Boolean", value: true, altValue: true },
            quickFooter: { type: "Boolean", value: true, altValue: true },
            quickAttack: { type: "Boolean", value: true, altValue: true },
            quickTemplate: { type: "Boolean", value: true, altValue: true },
            quickSave: { type: "Boolean", value: true, altValue: true },
            quickDamage: { type: "Array", value: [], altValue: [], context: [] },
            quickOther: { type: "Boolean", value: true, altValue: true, context: "" },
            consumeQuantity: { type: "Boolean", value: true, altValue: true },
            consumeUses: { type: "Boolean", value: true, altValue: true },
            consumeResource: { type: "Boolean", value: true, altValue: true },
            consumeRecharge: { type: "Boolean", value: true, altValue: true }
        },
        starshipweapons: {
            quickDesc: { type: "Boolean", value: false, altValue: false },
            quickFlavor: { type: "Boolean", value: true, altValue: true },
            quickFooter: { type: "Boolean", value: true, altValue: true },
            quickAttack: { type: "Boolean", value: true, altValue: true },
            quickSave: { type: "Boolean", value: true, altValue: true },
            quickCheck: { type: "Boolean", value: true, altValue: true },
            quickVersatile: { type: "Boolean", value: false, altValue: true },
            quickTemplate: { type: "Boolean", value: true, altValue: true },
            quickDamage: { type: "Array", value: [], altValue: [], context: [] },
            quickOther: { type: "Boolean", value: true, altValue: true, context: "" },
            consumeQuantity: { type: "Boolean", value: false, altValue: false },
            consumeUses: { type: "Boolean", value: false, altValue: true },
            consumeResource: { type: "Boolean", value: true, altValue: true }
        },
        power: {
            quickDesc: { type: "Boolean", value: true, altValue: true },
            quickFlavor: { type: "Boolean", value: true, altValue: true },
            quickFooter: { type: "Boolean", value: true, altValue: true },
            quickAttack: { type: "Boolean", value: true, altValue: true },
            quickVersatile: { type: "Boolean", value: false, altValue: false },
            quickSave: { type: "Boolean", value: true, altValue: true },
            quickDamage: { type: "Array", value: [], altValue: [], context: [] },
            quickOther: { type: "Boolean", value: true, altValue: true, context: "" }
        },
        ventures: {
            quickDesc: { type: "Boolean", value: true, altValue: true },
            quickFlavor: { type: "Boolean", value: true, altValue: true },
            quickFooter: { type: "Boolean", value: true, altValue: true },
            quickAttack: { type: "Boolean", value: true, altValue: true },
            quickTemplate: { type: "Boolean", value: true, altValue: true },
            quickSave: { type: "Boolean", value: true, altValue: true },
            quickDamage: { type: "Array", value: [], altValue: [], context: [] },
            quickOther: { type: "Boolean", value: true, altValue: true, context: "" },
            consumeQuantity: { type: "Boolean", value: true, altValue: true },
            consumeUses: { type: "Boolean", value: true, altValue: true },
            consumeResource: { type: "Boolean", value: true, altValue: true },
            consumeRecharge: { type: "Boolean", value: true, altValue: true }
        },
        vibroweapons: {
            quickDesc: { type: "Boolean", value: false, altValue: false },
            quickFlavor: { type: "Boolean", value: true, altValue: true },
            quickFooter: { type: "Boolean", value: true, altValue: true },
            quickAttack: { type: "Boolean", value: true, altValue: true },
            quickSave: { type: "Boolean", value: true, altValue: true },
            quickCheck: { type: "Boolean", value: true, altValue: true },
            quickVersatile: { type: "Boolean", value: false, altValue: true },
            quickTemplate: { type: "Boolean", value: true, altValue: true },
            quickDamage: { type: "Array", value: [], altValue: [], context: [] },
            quickOther: { type: "Boolean", value: true, altValue: true, context: "" },
            consumeQuantity: { type: "Boolean", value: false, altValue: false },
            consumeUses: { type: "Boolean", value: false, altValue: true },
            consumeResource: { type: "Boolean", value: true, altValue: true }
        }
    }
}
